print("Goodbye, World!, 1")
print("Goodbye, World!, 2")
print("Goodbye, World!, 3")
print("Goodbye, World!, 4")
print("Goodbye, World!, 5")
print("Goodbye, World!, 6")
print("Goodbye, World!, 7")
print("Goodbye, World!, 8")
